#   ____                     _        _____     _            _
#  |  _ \  ___  ___ ___   __| | ___  |_   _|_ _| | ___ _ __ | |_
#  | | | |/ _ \/ __/ _ \ / _` |/ _ \   | |/ _` | |/ _ \ '_ \| __|
#  | |_| |  __/ (_| (_) | (_| |  __/   | | (_| | |  __/ | | | |_
#  |____/ \___|\___\___/ \__,_|\___|   |_|\__,_|_|\___|_| |_|\__|

# Startship Config:


# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
# [package]
# disabled = true

[custom.bash]
command = "echo 🚀"
when = '[ "$STARSHIP_SHELL" == "bash" ]'

# Indicates when in fish shell.
[custom.fish]
command = "echo 🐠"
when = 'test "$STARSHIP_SHELL" = "fish"'

# Indicates when in Nushell.
[custom.nu]
command = "echo 🦀"
shell = 'bash'
when = '[ "$STARSHIP_SHELL" == "" ]' # not set in Nushell

# Timeout for Brew Command on upgrade
# command_timeout = 120